# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76456c0ac93f2b72a3c24a99966b5311d3a148489b328fa43bb9c84e400d3148af3c25e810a85440b745dd8d4b49a919ecccc9d33b6aede6b152b0819d9f7fc4

test:
  secret_key_base: 7d9ae6ae8a033e6e021e5c20726d2846d8ca3e38c0f4af170e874d340a496bad5f4b2bf3669a1ea5bcdec786eb399b17afa8c353e1313c6816f0d18bbcc1b5f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
